   [build]
     command = "npm run build"
     functions = "netlify/functions"
     publish = ".next"

   [[plugins]]
     package = "@netlify/plugin-nextjs"

   [functions]
     node_bundler = "esbuild"
